### ISSUE TITLE
Supported instruments

### ISSUE THREAD

**Issue by Michael-Hollister** [Michael-Hollister/Raspberry-Pi-Digital-Piano#5]

**Comment by Michael-Hollister** [comment]
Here are some instruments that quickly come to mind:
- Piano
- Guitar
- Violin
- Trumpet
- String ensemble
- And others...

Do any of you have a specific musical instrument you want included?

**Comment by Brian-Hoang** [comment]
We can keep it simple with three instruments. Piano, guitar, and trumpet are good general ones.
